importScripts('./order-alerts-worker.js');
const CACHE='john-erp-pwa-v8.22.64-pricing-menu-loader-fix';

const TX='./transaction-persistence-v8-22-13.js';
const MULTI='./multiempresa-v8-12-0.js';
const STABILITY='./production-stability-v8-10-5.js';
const PLATFORM='./platform-admin-v8-12-0.js';
const EXPERIENCE='./ecommerce-customer-experience-v8-13-0.js';
const HYDRATE='./server-catalog-hydration-v8-19.js';
const NEXTJS='./john-next-v8-17.js';
const NEXTCSS='./john-next-v8-17.css';
const COMMERCE='./commerce-engine-v8-22-0.js';
const CASHBACK='./cashback-engine-v8-22-42.js';
const CASHBACK_VISIBILITY='./cashback-visibility-hotfix-v8-22-43.js';
const COMMERCE_ENGAGEMENT='./commerce-engagement-erp-v8-22-44.js';
const MANAGEMENT='./management-engine-v8-22-0.js';
const USAGE='./erp-usage-v8-20.js';
const PUBLISH_SAFE='./catalog-publish-safe-v8-22-54.js';
const SYNC='./caseirinho-commerce-sync-v8-21.js';
const STRICT_MEDIA='./strict-media-upload-v8-22-5.js';
const MEDIA_SYNC='./media-sync-fix-v8-22-6.js';
const LAB='./pcp-laboratorio-v8-22-19.js';
const ETIQUETAS='./pcp-etiquetas-v8-22-20.js';
const FECHAMENTO='./fechamento-periodico-v8-22-21.js';
const PIX_STAY='./pix-config-stay-v8-22-22.js';
const UPSELL='./ecommerce-upsell-v8-22-23.js';
const PEDIDO_PRINT='./pedido-print-v8-22-24.js';
const PUBLISH_FIX='./catalog-publish-fix-v8-22-8.js';
const STORE_SETTINGS='./store-settings-sync-v8-22-13.js';
const PIX_DOCUMENT='./pix-document-fix-v8-22-13.js';
const PIX_OFFICIAL='./caseirinho-pix-config-v8-22-35.js';
const ORDER_REVISION='./ecommerce-order-revision-v8-22-37.js';
const PREREG='./ecommerce-preregistration-live-v8-22-38.js';
const DELIVERY_MOTO='./delivery-moto-config-v8-22-39.js';
const INBOX_FOCUS='./ecommerce-inbox-focus-v8-22-40.js';
const INTEGRITY='./production-integrity-v8-22-14.js';
const REAL_RECOVERY='./production-recovery-v8-22-15.js';
const RECOVERY='./ecommerce-recovery-v8-16-1.js';
const DEEP='./catalog-deep-recovery-v8-18-1.js';
const CENTRAL_FIX='./central-modules-hotfix-v8-22-2.js';
const USAGE_FIX='./erp-usage-v8-22-1.js';
const RELEASE='./release-consistency-v8-22-5.js';
const MACARRAO_RECOVERY='./macarrao-catalog-recovery-v8-22-25.js';
const CATEGORY_GRADE_SYNC='./catalog-category-grade-sync-v8-22-30.js';
const CATEGORY_SAVE='./product-category-store-sync-v8-22-31.js';

const TX_TAG='<script src="./transaction-persistence-v8-22-13.js?v=82244"></'+'script>';
const MULTI_TAG='<script src="./multiempresa-v8-12-0.js?v=82244"></'+'script>';
const STABILITY_TAG='<script src="./production-stability-v8-10-5.js?v=82244"></'+'script>';
const PLATFORM_TAG='<script src="./platform-admin-v8-12-0.js?v=82244"></'+'script>';
const EXPERIENCE_TAG='<script src="./ecommerce-customer-experience-v8-13-0.js?v=82244"></'+'script>';
const HYDRATE_TAG='<script src="./server-catalog-hydration-v8-19.js?v=82244"></'+'script>';
const NEXTJS_TAG='<script src="./john-next-v8-17.js?v=82244"></'+'script>';
const NEXTCSS_TAG='<link rel="stylesheet" href="./john-next-v8-17.css?v=82244">';
const COMMERCE_TAG='<script src="./commerce-engine-v8-22-0.js?v=82244"></'+'script>';
const CASHBACK_TAG='<script src="./cashback-engine-v8-22-42.js?v=82248"></'+'script>';
const CASHBACK_VISIBILITY_TAG='<script src="./cashback-visibility-hotfix-v8-22-43.js?v=82248"></'+'script>';
const COMMERCE_ENGAGEMENT_TAG='<script src="./commerce-engagement-erp-v8-22-44.js?v=82244"></'+'script>';
const MANAGEMENT_TAG='<script src="./management-engine-v8-22-0.js?v=82244"></'+'script>';
const USAGE_TAG='<script src="./erp-usage-v8-20.js?v=82244"></'+'script>';
const PUBLISH_SAFE_TAG='<script src="./catalog-publish-safe-v8-22-54.js?v=82254"></'+'script>';
const SYNC_TAG='<script src="./caseirinho-commerce-sync-v8-21.js?v=82254"></'+'script>';
const STRICT_MEDIA_TAG='<script src="./strict-media-upload-v8-22-5.js?v=82244"></'+'script>';
const MEDIA_SYNC_TAG='<script src="./media-sync-fix-v8-22-6.js?v=82244"></'+'script>';
const LAB_TAG='<script src="./pcp-laboratorio-v8-22-19.js?v=82244"></'+'script>';
const ETIQUETAS_TAG='<script src="./pcp-etiquetas-v8-22-20.js?v=82244"></'+'script>';
const FECHAMENTO_TAG='<script src="./fechamento-periodico-v8-22-21.js?v=82244"></'+'script>';
const PIX_STAY_TAG='<script src="./pix-config-stay-v8-22-22.js?v=82244"></'+'script>';
const UPSELL_TAG='<script src="./ecommerce-upsell-v8-22-23.js?v=82244"></'+'script>';
const PEDIDO_PRINT_TAG='<script src="./pedido-print-v8-22-24.js?v=82244"></'+'script>';
const PUBLISH_FIX_TAG='<script src="./catalog-publish-fix-v8-22-8.js?v=82244"></'+'script>';
const STORE_SETTINGS_TAG='<script src="./store-settings-sync-v8-22-13.js?v=82244"></'+'script>';
const PIX_DOCUMENT_TAG='<script src="./pix-document-fix-v8-22-13.js?v=82244"></'+'script>';
const PIX_OFFICIAL_TAG='<script src="./caseirinho-pix-config-v8-22-35.js?v=82244"></'+'script>';
const ORDER_REVISION_TAG='<script src="./ecommerce-order-revision-v8-22-37.js?v=82244"></'+'script>';
const PREREG_TAG='<script src="./ecommerce-preregistration-live-v8-22-38.js?v=82244"></'+'script>';
const DELIVERY_MOTO_TAG='<script src="./delivery-moto-config-v8-22-39.js?v=82244"></'+'script>';
const INBOX_FOCUS_TAG='<script src="./ecommerce-inbox-focus-v8-22-40.js?v=82244"></'+'script>';
const INTEGRITY_TAG='<script src="./production-integrity-v8-22-14.js?v=82244"></'+'script>';
const REAL_RECOVERY_TAG='<script src="./production-recovery-v8-22-15.js?v=82244"></'+'script>';
const RECOVERY_TAG='<script src="./ecommerce-recovery-v8-16-1.js?v=82244"></'+'script>';
const DEEP_TAG='<script src="./catalog-deep-recovery-v8-18-1.js?v=82244"></'+'script>';
const CENTRAL_FIX_TAG='<script src="./central-modules-hotfix-v8-22-2.js?v=82244"></'+'script>';
const USAGE_FIX_TAG='<script src="./erp-usage-v8-22-1.js?v=82244"></'+'script>';
const RELEASE_TAG='<script src="./release-consistency-v8-22-5.js?v=82244"></'+'script>';
const MACARRAO_RECOVERY_TAG='<script src="./macarrao-catalog-recovery-v8-22-25.js?v=82244"></'+'script>';
const CATEGORY_GRADE_SYNC_TAG='<script src="./catalog-category-grade-sync-v8-22-30.js?v=82244"></'+'script>';
const CATEGORY_SAVE_TAG='<script src="./product-category-store-sync-v8-22-31.js?v=82244"></'+'script>';
const ECOMMERCE_SUBMODULE_TAG='<script src="./ecommerce-submodule-media-v8-22-17.js?v=82218"></'+'script>';
const PRICING_PACK_TAG='<script src="./pricing-pack-offers-v8-22-57.js?v=82264"></'+'script>';

const SHELL=['./order-amounts.js','./order-alerts-worker.js','./order-alerts-v8-22-51.js','./','./index.html','./manifest.webmanifest','./offline.html','./icons/icon-192.png','./icons/icon-512.png','./icons/icon-maskable-512.png','./icons/apple-touch-icon.png',TX,MULTI,STABILITY,PLATFORM,EXPERIENCE,HYDRATE,NEXTJS,NEXTCSS,COMMERCE,CASHBACK,CASHBACK_VISIBILITY,COMMERCE_ENGAGEMENT,MANAGEMENT,USAGE,PUBLISH_SAFE,SYNC,STRICT_MEDIA,MEDIA_SYNC,LAB,ETIQUETAS,FECHAMENTO,PIX_STAY,UPSELL,PEDIDO_PRINT,PUBLISH_FIX,STORE_SETTINGS,PIX_DOCUMENT,PIX_OFFICIAL,ORDER_REVISION,PREREG,DELIVERY_MOTO,INBOX_FOCUS,INTEGRITY,REAL_RECOVERY,RECOVERY,DEEP,CENTRAL_FIX,USAGE_FIX,RELEASE,MACARRAO_RECOVERY,CATEGORY_GRADE_SYNC,CATEGORY_SAVE,'./ecommerce-submodule-media-v8-22-17.js','./pricing-pack-offers-v8-22-57.js?v=82263'];

async function cacheShell(){const c=await caches.open(CACHE);for(const url of SHELL){try{const r=await fetch(url,{cache:'reload'});if(r.ok)await c.put(url,r.clone())}catch(_){}}}
function injectBefore(html,needle,tag){if(html.includes(needle))return html;const low=html.toLowerCase(),p=low.lastIndexOf('</body>');return p>=0?html.slice(0,p)+tag+html.slice(p):html+tag}
function ensurePricingPackScript(html,tag){const re=/<script\b[^>]*src=["'][^"']*pricing-pack-offers-v8-22-57\.js[^"']*["'][^>]*>\s*<\/script\s*>/gi;html=html.replace(re,'');const p=html.toLowerCase().lastIndexOf('</body>');return p>=0?html.slice(0,p)+tag+html.slice(p):html+tag}
function injectHead(html,needle,tag){if(html.includes(needle))return html;const low=html.toLowerCase(),p=low.lastIndexOf('</head>');return p>=0?html.slice(0,p)+tag+html.slice(p):tag+html}
async function injectScripts(response){
  if(!response)return response;const ct=response.headers.get('content-type')||'';if(!ct.includes('text/html'))return response;let html=await response.text();
  html=html.replace(/<script[^>]+ecommerce-order-revision-v8-22-36\.js[^>]*><\/script>/gi,'');
  html=html.replace(/<script[^>]+ecommerce-submodule-media-v8-22-17\.js[^>]*><\/script>/gi,'');
  html=injectBefore(html,'order-alerts-v8-22-51.js','<script src="./order-alerts-v8-22-51.js?v=82251"></'+'script>');
  html=injectHead(html,'order-amounts.js','<script src="./order-amounts.js?v=20261004"></'+'script>');html=injectHead(html,'transaction-persistence-v8-22-13.js',TX_TAG);
  html=injectHead(html,'multiempresa-v8-12-0.js',MULTI_TAG);
  html=injectHead(html,'john-next-v8-17.css',NEXTCSS_TAG);
  html=injectBefore(html,'production-stability-v8-10-5.js',STABILITY_TAG);
  html=injectBefore(html,'platform-admin-v8-12-0.js',PLATFORM_TAG);
  html=injectBefore(html,'ecommerce-customer-experience-v8-13-0.js',EXPERIENCE_TAG);
  html=injectBefore(html,'server-catalog-hydration-v8-19.js',HYDRATE_TAG);
  html=injectBefore(html,'john-next-v8-17.js',NEXTJS_TAG);
  html=injectBefore(html,'commerce-engine-v8-22-0.js',COMMERCE_TAG);
  html=injectBefore(html,'cashback-engine-v8-22-42.js',CASHBACK_TAG);
  html=injectBefore(html,'cashback-visibility-hotfix-v8-22-43.js',CASHBACK_VISIBILITY_TAG);
  html=injectBefore(html,'commerce-engagement-erp-v8-22-44.js',COMMERCE_ENGAGEMENT_TAG);
  html=injectBefore(html,'management-engine-v8-22-0.js',MANAGEMENT_TAG);
  html=injectBefore(html,'erp-usage-v8-20.js',USAGE_TAG);
  html=injectBefore(html,'catalog-publish-safe-v8-22-54.js',PUBLISH_SAFE_TAG);
  html=injectBefore(html,'caseirinho-commerce-sync-v8-21.js',SYNC_TAG);
  html=injectBefore(html,'strict-media-upload-v8-22-5.js',STRICT_MEDIA_TAG);
  html=injectBefore(html,'media-sync-fix-v8-22-6.js',MEDIA_SYNC_TAG);
  html=injectBefore(html,'pcp-laboratorio-v8-22-19.js',LAB_TAG);
  html=injectBefore(html,'pcp-etiquetas-v8-22-20.js',ETIQUETAS_TAG);
  html=injectBefore(html,'fechamento-periodico-v8-22-21.js',FECHAMENTO_TAG);
  html=injectBefore(html,'pix-config-stay-v8-22-22.js',PIX_STAY_TAG);
  html=injectBefore(html,'ecommerce-upsell-v8-22-23.js',UPSELL_TAG);
  html=injectBefore(html,'pedido-print-v8-22-24.js',PEDIDO_PRINT_TAG);
  html=injectBefore(html,'catalog-publish-fix-v8-22-8.js',PUBLISH_FIX_TAG);
  html=injectBefore(html,'store-settings-sync-v8-22-13.js',STORE_SETTINGS_TAG);
  html=injectBefore(html,'pix-document-fix-v8-22-13.js',PIX_DOCUMENT_TAG);
  html=injectBefore(html,'caseirinho-pix-config-v8-22-35.js',PIX_OFFICIAL_TAG);
  html=injectBefore(html,'ecommerce-order-revision-v8-22-37.js',ORDER_REVISION_TAG);
  html=injectBefore(html,'ecommerce-preregistration-live-v8-22-38.js',PREREG_TAG);
  html=injectBefore(html,'delivery-moto-config-v8-22-39.js',DELIVERY_MOTO_TAG);
  html=injectBefore(html,'production-integrity-v8-22-14.js',INTEGRITY_TAG);
  html=injectBefore(html,'production-recovery-v8-22-15.js',REAL_RECOVERY_TAG);
  html=injectBefore(html,'ecommerce-recovery-v8-16-1.js',RECOVERY_TAG);
  html=injectBefore(html,'catalog-deep-recovery-v8-18-1.js',DEEP_TAG);
  html=injectBefore(html,'central-modules-hotfix-v8-22-2.js',CENTRAL_FIX_TAG);
  html=injectBefore(html,'erp-usage-v8-22-1.js',USAGE_FIX_TAG);
  html=injectBefore(html,'release-consistency-v8-22-5.js',RELEASE_TAG);
  html=injectBefore(html,'macarrao-catalog-recovery-v8-22-25.js',MACARRAO_RECOVERY_TAG);
  html=injectBefore(html,'catalog-category-grade-sync-v8-22-30.js',CATEGORY_GRADE_SYNC_TAG);
  html=injectBefore(html,'ecommerce-submodule-media-v8-22-17.js',ECOMMERCE_SUBMODULE_TAG);
  html=ensurePricingPackScript(html,PRICING_PACK_TAG);
  html=injectBefore(html,'product-category-store-sync-v8-22-31.js',CATEGORY_SAVE_TAG);
  html=injectBefore(html,'ecommerce-inbox-focus-v8-22-40.js',INBOX_FOCUS_TAG);
  const h=new Headers(response.headers);h.delete('content-length');h.set('Cache-Control','no-cache, no-store, must-revalidate');return new Response(html,{status:response.status,statusText:response.statusText,headers:h});
}
self.addEventListener('install',e=>e.waitUntil(cacheShell().then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE&&k.startsWith('john-erp-pwa-')).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',e=>{if(e.data&&e.data.type==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(u.origin!==self.location.origin||e.request.method!=='GET')return;if(/\/recuperar-macarrao-v8-22-(?:25|26)\.html$/.test(u.pathname)){e.respondWith(fetch(e.request,{cache:'no-store'}).catch(()=>caches.match(e.request)));return}if(e.request.mode==='navigate'){e.respondWith((async()=>{try{const net=await fetch(e.request,{cache:'no-store'}),out=await injectScripts(net);if(out&&out.ok)caches.open(CACHE).then(c=>c.put('./index.html',out.clone())).catch(()=>{});return out}catch(_){const cached=await caches.match('./index.html')||await caches.match('./offline.html');return injectScripts(cached)}})());return}e.respondWith(fetch(e.request,{cache:'no-store'}).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put(e.request,r.clone())).catch(()=>{});return r}).catch(()=>caches.match(e.request)))});

