const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const ce=fs.readFileSync(path.join(root,'commerce-engine-v8-22-0.js'),'utf8');
const mg=fs.readFileSync(path.join(root,'management-engine-v8-22-0.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
test('Motor Comercial abre no centro',()=>{assert.match(ce,/p\.id='motorComercial'/);assert.match(ce,/function showCenter\(\)/);assert.doesNotMatch(ce,/position:fixed;inset:0/)});
test('Central Gerencial abre no centro',()=>{assert.match(mg,/p\.id='centralGerencial'/);assert.match(mg,/function showCenter\(\)/);assert.doesNotMatch(mg,/position:fixed;inset:0/)});
test('menu mantém os dois como módulos próprios',()=>{assert.match(html,/nome:'Motor Comercial'/);assert.match(html,/nome:'Central Gerencial'/)});
