const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const ce=fs.readFileSync(path.join(root,'commerce-engine-v8-15-0.js'),'utf8');
const mg=fs.readFileSync(path.join(root,'management-engine-v8-16-0.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
test('Motor Comercial abre no centro',()=>{assert.match(ce,/page\.id='motorComercial'/);assert.match(ce,/showCenterPage\('motorComercial'\)/);assert.doesNotMatch(ce,/E\('johnCE815'\)\.classList\.add\('open'\)/)});
test('Central Gerencial abre no centro',()=>{assert.match(mg,/page\.id='centralGerencial'/);assert.match(mg,/showCenterPage\('centralGerencial'\)/);assert.doesNotMatch(mg,/E\('johnMG816'\)\.classList\.add\('open'\)/)});
test('menu mantém os dois como módulos próprios',()=>{assert.match(html,/nome:'Motor Comercial'/);assert.match(html,/nome:'Central Gerencial'/)});
