const CACHE="john-erp-pwa-v8.22.15-real-recovery";
const RECOVERY="./production-recovery-v8-22-15.js";
const SHELL=["./","./index.html","./manifest.webmanifest","./offline.html","./icons/icon-192.png","./icons/icon-512.png","./icons/icon-maskable-512.png","./icons/apple-touch-icon.png",RECOVERY];
const RECOVERY_TAG='<script src="./production-recovery-v8-22-15.js?v=82215"></'+'script>';
async function cacheShell(){const c=await caches.open(CACHE);for(const url of SHELL){try{const r=await fetch(url,{cache:'reload'});if(r.ok)await c.put(url,r.clone())}catch(_){}}}
async function injectRecovery(response){if(!response)return response;const ct=response.headers.get('content-type')||'';if(!ct.includes('text/html'))return response;let html=await response.text();if(!html.includes('production-recovery-v8-22-15.js')){const p=html.toLowerCase().lastIndexOf('</body>');html=p>=0?html.slice(0,p)+RECOVERY_TAG+html.slice(p):html+RECOVERY_TAG}const h=new Headers(response.headers);h.delete('content-length');h.set('Cache-Control','no-cache, no-store, must-revalidate');return new Response(html,{status:response.status,statusText:response.statusText,headers:h})}
self.addEventListener("install",e=>e.waitUntil(cacheShell().then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE&&k.startsWith('john-erp-pwa-')).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener("message",e=>{if(e.data&&e.data.type==="SKIP_WAITING")self.skipWaiting()});
self.addEventListener("fetch",e=>{const u=new URL(e.request.url);if(u.origin!==self.location.origin||e.request.method!=="GET")return;if(e.request.mode==="navigate"){e.respondWith((async()=>{try{const r=await fetch(e.request,{cache:"no-store"}),out=await injectRecovery(r);if(out&&out.ok)caches.open(CACHE).then(c=>c.put("./index.html",out.clone())).catch(()=>{});return out}catch(_){return injectRecovery(await caches.match("./index.html")||await caches.match("./offline.html"))}})());return}e.respondWith(fetch(e.request,{cache:'no-store'}).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put(e.request,r.clone())).catch(()=>{});return r}).catch(()=>caches.match(e.request)))});